# plex_auth/utils/exceptions.py


class PlexManagerError(Exception):
    """Custom exception for Plex API related errors"""

    pass
